[2024-11-10T13:54:47.981+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-10T13:54:48.323+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_dag.extract_csv2 manual__2024-11-10T13:30:30.447964+00:00 [queued]>
[2024-11-10T13:54:48.343+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_dag.extract_csv2 manual__2024-11-10T13:30:30.447964+00:00 [queued]>
[2024-11-10T13:54:48.345+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-10T13:54:48.389+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_csv2> on 2024-11-10 13:30:30.447964+00:00
[2024-11-10T13:54:48.412+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=141) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-10T13:54:48.415+0000] {standard_task_runner.py:72} INFO - Started process 158 to run task
[2024-11-10T13:54:48.423+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_dag', 'extract_csv2', 'manual__2024-11-10T13:30:30.447964+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmpu1w3jiyu']
[2024-11-10T13:54:48.425+0000] {standard_task_runner.py:105} INFO - Job 49: Subtask extract_csv2
[2024-11-10T13:54:48.519+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_dag.extract_csv2 manual__2024-11-10T13:30:30.447964+00:00 [running]> on host 1669fe1f842b
[2024-11-10T13:54:48.760+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_dag' AIRFLOW_CTX_TASK_ID='extract_csv2' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T13:30:30.447964+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T13:30:30.447964+00:00'
[2024-11-10T13:54:48.763+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-10T13:54:48.765+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-10T13:54:48.766+0000] {logging_mixin.py:190} INFO - Current task name:extract_csv2 state:running start_date:2024-11-10 13:54:48.325057+00:00
[2024-11-10T13:54:48.766+0000] {logging_mixin.py:190} INFO - Dag name:extract_dag and current dag run status:running
[2024-11-10T13:54:48.767+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-10T13:54:48.781+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_dag.py", line 19, in extract_from_csv
    return pd.read_csv(file_path)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dell\\Downloads\\Big Data\\csv_files/50000 Sales Records.csv'
[2024-11-10T13:54:48.807+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-10T13:54:48.808+0000] {logging_mixin.py:190} INFO - Task start:2024-11-10 13:54:48.325057+00:00 end:2024-11-10 13:54:48.806901+00:00 duration:0.481844
[2024-11-10T13:54:48.809+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_csv2> dag:<DAG: extract_dag> dagrun:<DagRun extract_dag @ 2024-11-10 13:30:30.447964+00:00: manual__2024-11-10T13:30:30.447964+00:00, state:running, queued_at: 2024-11-10 13:30:30.503029+00:00. externally triggered: True>
[2024-11-10T13:54:48.810+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'C:\\Users\\dell\\Downloads\\Big Data\\csv_files/50000 Sales Records.csv'
[2024-11-10T13:54:48.810+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=extract_dag, task_id=extract_csv2, run_id=manual__2024-11-10T13:30:30.447964+00:00, execution_date=20241110T133030, start_date=20241110T135448, end_date=20241110T135448
[2024-11-10T13:54:48.845+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-10T13:54:48.846+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 49 for task extract_csv2 ([Errno 2] No such file or directory: 'C:\\Users\\dell\\Downloads\\Big Data\\csv_files/50000 Sales Records.csv'; 158)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_dag.py", line 19, in extract_from_csv
    return pd.read_csv(file_path)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dell\\Downloads\\Big Data\\csv_files/50000 Sales Records.csv'
[2024-11-10T13:54:48.891+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-10T13:54:48.923+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-10T13:54:48.932+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
