[2024-11-10T13:48:55.435+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-10T13:48:55.566+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_dag.extract_mysql manual__2024-11-10T13:46:28.041003+00:00 [queued]>
[2024-11-10T13:48:55.601+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_dag.extract_mysql manual__2024-11-10T13:46:28.041003+00:00 [queued]>
[2024-11-10T13:48:55.608+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-10T13:48:55.721+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_mysql> on 2024-11-10 13:46:28.041003+00:00
[2024-11-10T13:48:55.817+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=97) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-10T13:48:55.828+0000] {standard_task_runner.py:72} INFO - Started process 119 to run task
[2024-11-10T13:48:55.830+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_dag', 'extract_mysql', 'manual__2024-11-10T13:46:28.041003+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmpfwrdjova']
[2024-11-10T13:48:55.833+0000] {standard_task_runner.py:105} INFO - Job 43: Subtask extract_mysql
[2024-11-10T13:48:56.045+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_dag.extract_mysql manual__2024-11-10T13:46:28.041003+00:00 [running]> on host 1669fe1f842b
[2024-11-10T13:48:58.214+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_dag' AIRFLOW_CTX_TASK_ID='extract_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T13:46:28.041003+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T13:46:28.041003+00:00'
[2024-11-10T13:48:58.218+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-10T13:48:58.219+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-10T13:48:58.220+0000] {logging_mixin.py:190} INFO - Current task name:extract_mysql state:running start_date:2024-11-10 13:48:55.574638+00:00
[2024-11-10T13:48:58.220+0000] {logging_mixin.py:190} INFO - Dag name:extract_dag and current dag run status:running
[2024-11-10T13:48:58.221+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-10T13:49:01.028+0000] {base.py:84} INFO - Retrieving connection 'mysql_xampp_conn'
[2024-11-10T13:49:01.526+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_dag.py", line 30, in extract_from_mysql_and_save_as_csv
    tables_df = mysql_hook.get_pandas_df("SHOW TABLES")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 315, in get_pandas_df
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/hooks/mysql.py", line 200, in get_conn
    return MySQLdb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)")
[2024-11-10T13:49:01.672+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-10T13:49:01.673+0000] {logging_mixin.py:190} INFO - Task start:2024-11-10 13:48:55.574638+00:00 end:2024-11-10 13:49:01.671543+00:00 duration:6.096905
[2024-11-10T13:49:01.675+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_mysql> dag:<DAG: extract_dag> dagrun:<DagRun extract_dag @ 2024-11-10 13:46:28.041003+00:00: manual__2024-11-10T13:46:28.041003+00:00, state:running, queued_at: 2024-11-10 13:46:28.090183+00:00. externally triggered: True>
[2024-11-10T13:49:01.675+0000] {logging_mixin.py:190} INFO - Failure caused by (2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)")
[2024-11-10T13:49:01.676+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_dag, task_id=extract_mysql, run_id=manual__2024-11-10T13:46:28.041003+00:00, execution_date=20241110T134628, start_date=20241110T134855, end_date=20241110T134901
[2024-11-10T13:49:01.708+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-10T13:49:01.709+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 43 for task extract_mysql ((2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)"); 119)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_dag.py", line 30, in extract_from_mysql_and_save_as_csv
    tables_df = mysql_hook.get_pandas_df("SHOW TABLES")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 315, in get_pandas_df
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/hooks/mysql.py", line 200, in get_conn
    return MySQLdb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)")
[2024-11-10T13:49:01.767+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-10T13:49:01.797+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-10T13:49:01.805+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
