[2024-11-10T14:11:40.663+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-10T14:11:40.690+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_dag.extract_csv1 manual__2024-11-10T14:02:22.629174+00:00 [queued]>
[2024-11-10T14:11:40.703+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_dag.extract_csv1 manual__2024-11-10T14:02:22.629174+00:00 [queued]>
[2024-11-10T14:11:40.706+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-10T14:11:40.768+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_csv1> on 2024-11-10 14:02:22.629174+00:00
[2024-11-10T14:11:40.864+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=64) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-10T14:11:40.874+0000] {standard_task_runner.py:72} INFO - Started process 76 to run task
[2024-11-10T14:11:40.897+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_dag', 'extract_csv1', 'manual__2024-11-10T14:02:22.629174+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmp83kp9w7r']
[2024-11-10T14:11:40.901+0000] {standard_task_runner.py:105} INFO - Job 121: Subtask extract_csv1
[2024-11-10T14:11:41.327+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_dag.extract_csv1 manual__2024-11-10T14:02:22.629174+00:00 [running]> on host 1669fe1f842b
[2024-11-10T14:11:41.888+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_dag' AIRFLOW_CTX_TASK_ID='extract_csv1' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T14:02:22.629174+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T14:02:22.629174+00:00'
[2024-11-10T14:11:41.901+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-10T14:11:41.902+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-10T14:11:41.903+0000] {logging_mixin.py:190} INFO - Current task name:extract_csv1 state:running start_date:2024-11-10 14:11:40.691534+00:00
[2024-11-10T14:11:41.904+0000] {logging_mixin.py:190} INFO - Dag name:extract_dag and current dag run status:running
[2024-11-10T14:11:41.911+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-10T14:11:41.931+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_dag.py", line 19, in extract_from_csv
    return pd.read_csv(file_path)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dell\\Downloads\\Big Data\\csv_files/sales_data_sample.csv'
[2024-11-10T14:11:42.110+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-10T14:11:42.111+0000] {logging_mixin.py:190} INFO - Task start:2024-11-10 14:11:40.691534+00:00 end:2024-11-10 14:11:42.110051+00:00 duration:1.418517
[2024-11-10T14:11:42.112+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_csv1> dag:<DAG: extract_dag> dagrun:<DagRun extract_dag @ 2024-11-10 14:02:22.629174+00:00: manual__2024-11-10T14:02:22.629174+00:00, state:running, queued_at: 2024-11-10 14:02:22.721198+00:00. externally triggered: True>
[2024-11-10T14:11:42.113+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'C:\\Users\\dell\\Downloads\\Big Data\\csv_files/sales_data_sample.csv'
[2024-11-10T14:11:42.113+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=extract_dag, task_id=extract_csv1, run_id=manual__2024-11-10T14:02:22.629174+00:00, execution_date=20241110T140222, start_date=20241110T141140, end_date=20241110T141142
[2024-11-10T14:11:44.071+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-10T14:11:44.073+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 121 for task extract_csv1 ([Errno 2] No such file or directory: 'C:\\Users\\dell\\Downloads\\Big Data\\csv_files/sales_data_sample.csv'; 76)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_dag.py", line 19, in extract_from_csv
    return pd.read_csv(file_path)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dell\\Downloads\\Big Data\\csv_files/sales_data_sample.csv'
[2024-11-10T14:11:44.104+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-10T14:11:44.127+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-10T14:11:44.144+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
